version: '3'
services:
    bitpass:
        build: .
        volumes:
            - $GPG_HOME:/gpg_home
            - $PASSWORD_STORE:/password-store
        environment:
            - BW_USER=$BW_USER
            - BW_PASSWORD=$BW_PASSWORD
            - PUBLIC_GPG_NAME=$PUBLIC_GPG_NAME
            # If you want to get notifications on leaked passwords
            # we are using apprise here https://github.com/caronc/apprise
            - NOTIF_URL=$NOTIF_URL
